---
- name: Terminal Developer Environment Playbook
  hosts: all
  vars_files:
    - "vars/main.yml"
  gather_facts: true
  tasks:
    - name: Ensure system is up-to-date and required packages are present
      ansible.builtin.import_tasks: "tasks/packages.yml"
